pygments: true
permalink: /blog/:title
auto: true
website: https://www.ksornberger.com
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  - jekyll-seo-tag


title: Kevin Sornberger